# frontend/pubspec.yaml
name: asso_platform
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.4.2
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: any
  firebase_messaging: any
  flutter_dotenv: ^5.1.0
  url_strategy: any
  shared_preferences: ^2.2.0
  crypto: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true     
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output-dir: lib/generated
