name = "assopourtous-api"
main = "src/index.ts"
compatibility_date = "2024-07-11" # не 2025!
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "asso-db"
database_id = "a1273069-a1cf-4c48-9611-747039604f69"

[vars]
JWT_SECRET = "supersecret"
