name = "assopourtous-api"
main = "src/index.ts"
compatibility_date = "2024-07-11"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"

# Привязка маршрута
routes = [
  { pattern = "assopourtous.com/api/*", zone_name = "assopourtous.com" }
]

# Привязка D1 базы
[[d1_databases]]
binding = "DB"
database_name = "asso-db"
database_id = "a1273069-a1cf-4c48-9611-747039604f69"

# Переменные окружения
[vars]
JWT_SECRET = "supersecret"
