name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Worker ----------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g wrangler
      - run: |
          cd backend/worker
          npm ci
          npm run deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      # ---------- Flutter Web ----------
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
      - run: |
          cd frontend/app
          flutter pub get
          flutter build web --release

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: "platform-pwa"
          directory: "frontend/app/build/web"
